spring:
  #SQL
  datasource:
    url: jdbc:postgresql://localhost:5432/security_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  #liquibase
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: classpath:db.changelog/db.changelog-master.xml
  #JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
